name: yash
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  appwrite: ^18.0.0
  intl: ^0.20.2
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.2.1
  get_storage: ^2.1.1
  icons_plus: ^5.0.0
  lottie: ^3.3.1
  flutter_svg: ^2.2.0
  http: ^1.5.0
  carousel_slider: ^5.1.1
  webview_flutter: ^4.13.0
  syncfusion_flutter_pdfviewer: ^31.1.19
  no_screenshot: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/k2d/
    - assets/images/icons/
    - assets/images/logo/
    - assets/lottie/
    - assets/preview/
    - .env

  fonts:
    - family: K2D
      fonts:
        - asset: assets/fonts/k2d/K2D-Thin.ttf
          weight: 100
        - asset: assets/fonts/k2d/K2D-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/k2d/K2D-Light.ttf
          weight: 300
        - asset: assets/fonts/k2d/K2D-Regular.ttf
          weight: 400
        - asset: assets/fonts/k2d/K2D-Medium.ttf
          weight: 500
        - asset: assets/fonts/k2d/K2D-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/k2d/K2D-Bold.ttf
          weight: 700
        - asset: assets/fonts/k2d/K2D-ExtraBold.ttf
          weight: 800
flutter_intl:
  enabled: true
